[package]
name = "jb"
version = "0.1.0"
edition = "2021"

[dependencies]
jb_derived = { path = "../jb_derived" }
jb_platform = { path = "../jb_platform" }
regex = "1.10.4"
rustls = {version = "0.23", features=["ring"], default-features = false}