unstable_features = true
max_width = 160
binop_separator = "Back"
use_small_heuristics = "Off"
fn_single_line = false
indent_style = "Visual"
imports_granularity = "Module"
reorder_impl_items = true
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 120
struct_field_align_threshold = 120