[package]
name = "metalberto"
version = "0.1.0"
edition = "2021"

[dependencies]
jb = { path = "../jb" }
jb_derived = { path = "../jb_derived" }
jb_platform = { path = "../jb_platform" }
rustls = {version = "0.23", features=["ring"], default-features = true}
webpki-roots = "0.26.3"